dist: xenial

language: python

stages:
  - lint
  - primary
  - rusty
  - secondary

python:
  - '3.7'
  - '3.6'
  - '2.7'
  - '3.5'

env:
  - MOLT_BUILD_PYTHON=python

cache:
  - /home/travis/.cargo
  - /home/travis/.rustup
  - ./target
  - cargo
  - pip

jobs:
  fast_finish: true
  include:
    - stage: lint
      name: Python 3 Lint
      python: '3.7'
      install: pip install black flake8
      script:
        - black --check python vendor
        - flake8 python vendor
    - name: Python 2 Lint
      python: '2.7'
      install: pip install flake8
      script: flake8 python vendor
    - name: Rust Lint
      python: '3.7'
      before_install:
        - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs
          | sh -s -- --default-toolchain=stable -y"
        - export PATH=$HOME/.cargo/bin:$PATH
      install: rustup component add clippy
      script: cargo clippy

    - stage: primary
      python: '3.7'
      install: pip install tox-travis
      script: tox
    - python: '2.7'
      install: pip install tox-travis
      script: tox

    - stage: rusty
      python: '3.7'
      before_install:
        - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs
          | sh -s -- --default-toolchain=stable -y"
        - export PATH=$HOME/.cargo/bin:$PATH
      script: cargo test

    - stage: secondary
      python: '3.6'
      install: pip install tox-travis
      script: tox
    - python: '3.5'
      install: pip install tox-travis
      script: tox
