dist: xenial

stages:
  - lint
  - primary
  - secondary

cache:
  directories:
    - /home/travis/.cargo
    - ./tox
  pip: true

before_cache:
  - rm -rf /home/travis/.cargo/registry

jobs:
  fast_finish: true
  allow_failures:
    - python: '3.8-dev'
    - rust: nightly

  include:
    - stage: lint
      name: Python 3 Lint
      language: python
      python: '3.7'
      install: pip install black flake8
      script:
        - black --check python vendor
        - flake8 python vendor
    - name: Python 2 Lint
      language: python
      python: '2.7'
      install: pip install flake8
      script: flake8 python vendor

    - stage: primary
      language: python
      python: '3.7'
      install: pip install tox-travis
      script: tox
    - language: python
      python: '2.7'
      install: pip install tox-travis
      script: tox
    - language: rust
      rust: stable
      addons:
        apt:
          packages:
            - python3.5
            - python-virtualenv
      env:
        - MOLT_BUILD_PYTHON=./.tox/py35/bin/python
      install:
        - rustup component add clippy
        - virtualenv --python=python2.7 ./.tox/py27
        - virtualenv --python=python3.5 ./.tox/py35
      script:
        - cargo clippy
        - cargo test

    - stage: secondary
      language: python
      python: '3.6'
      install: pip install tox-travis
      script: tox
    - language: python
      python: '3.5'
      install: pip install tox-travis
      script: tox
    - language: rust
      rust: nightly
      addons:
        apt:
          packages:
            - python3.5
            - python-virtualenv
      env:
        - MOLT_BUILD_PYTHON=./.tox/py35/bin/python
      install:
        - rustup component add clippy
        - virtualenv --python=python2.7 ./.tox/py27
        - virtualenv --python=python3.5 ./.tox/py35
      script: cargo test
    - language: python
      python: '3.8-dev'
      install: pip install tox-travis
      script: tox
