dist: xenial

language: python

python:
  - '3.7'
  - '3.6'
  - '2.7'
  - '3.5'

env:
  - MOLT_BUILD_PYTHON=python

cache:
  - /home/travis/.cargo
  - /home/travis/.rustup
  - ./target
  - cargo
  - pip

before_install:
  - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs
     | sh -s -- --default-toolchain=stable -y"
  - export PATH=$HOME/.cargo/bin:$PATH

install:
  - pip install black flake8 tox-travis
  - rustup component add clippy

script:
  - flake8 python vendor
  - black --check python vendor
  - tox
  - cargo clippy
  - cargo test
